INV_Licenses =
    [

        ["car",[licenseflag3,southlicense1,licenseflag5,pmcatm,university],localize "STRS_license_car",25000],
        ["truck",[licenseflag3,southlicense1,pmcatm,licenseflag5,university],localize "STRS_license_truck",82500],
        ["oil",[Oil_1,Oil_1,Oil_2,Oil_2,Oil_2],"Oil Processor's License",45000],
        ["diamond",[Diamond_1,Diamond_1,Diamond_1,Diamond_1,Diamond_1],"Diamond Processor's License",95000],
        ["glassblowing",[Glassblower,Glassblower,Glassblower,Glassblower,Glassblower],localize "STRS_license_glassblowerlicense",65000],
        ["cocaine ga1",[gangarea1,gangarea1,gangarea1,gangarea1,gangarea1],"GA1 Cocaine Processing Training",450000],
        ["lsd ga1",[gangarea1,gangarea1,gangarea1,gangarea1,gangarea1],"GA1 LSD Processing Training",300000],
        ["heroin ga2",[gangarea2,gangarea2,gangarea2,gangarea2,gangarea2],"GA2 Heroin Processing Training",500000],
        ["lsd ga2",[gangarea2,gangarea2,gangarea2,gangarea2,gangarea2],"GA2 LSD Processing Training",300000],
        ["heroin ga3",[gangarea3,gangarea3,gangarea3,gangarea3,gangarea3],"GA3 Heroin Processing Training",500000],
        ["marijuana ga3",[gangarea3,gangarea3,gangarea3,gangarea3,gangarea3],"GA3 Marijuana Processing Training",170000],
        ["air",[licenseflag3,licenseflag5,southlicense1,pmcatm,pmcatm],localize "STRS_license_air",500000],
		["jet",[licenseflag3,licenseflag5,southlicense1,pmcatm,pmcatm],localize "STRS_license_jet",400000],
        ["pistollicense",[pmcatm,licenseflag2,licenseflag2,licenseflag2,pmcatm],"Pistol License",40000],
        ["riflelicense",[pmcatm,licenseflag2,licenseflag2,licenseflag2,pmcatm],"Rifle License",125000],
        ["automatic",[pmcatm,licenseflag2,licenseflag2,licenseflag2,pmcatm],"Assault Weapon License",300000],
		["engineer",[licenseflag3,pmcatm,southlicense1,atmins,atm5,university],localize "STRS_license_engineer",65000],
        ["bomb",[airshop3,atmins,atm5,terrorshop,terrorshop],"Combat Training",350000],
        ["probator",[copbank,copbank,copbank,copbank,copbank],localize "STRS_license_probator",10000],
        ["patrol_training",[copbank,copbank,copbank,copbank,copbank],localize "STRS_license_coppatrol",150000],
        ["response_training",[copbank,copbank,copbank,copbank,copbank],localize "STRS_license_copresponse",350000],
        ["sobr_training",[copbank,copbank,copbank,copbank,copbank],localize "STRS_license_copswat",800000],
        ["air_support_training",[copbank,copbank,copbank,copbank,copbank],localize "STRS_license_copairsupport",525000],
        ["passport_civilian",[licenseflag3,licenseflag3,licenseflag5,licenseflag5,licenseflag5],"Takistani Passport",35000],
        ["pmc_license_journeyman",[safelicense,safelicense,safelicense,safelicense,safelicense],"PMC Journeyman License",1500000],
        ["pmc_license_defense",[pmcatm,pmcatm,pmcatm,pmcatm,pmcatm],"PMC Defense License",350000],
        ["pmc_license_air",[pmcatm,pmcatm,pmcatm,pmcatm,pmcatm],"PMC Pilot License",850000],
		["soviet_vehicles",[atmins,atm5,airshop3,terrorshop,terrorshop],"Soviet Vehicle Training",500000],
        ["soviet_air_veh",[atmins,atm5,airshop3,terrorshop,terrorshop],"Soviet Aircraft Training",300000],
        ["paramedic_license",[tdoc,tdoc,tdoc_1,tdoc_1,tdoc_1],"Paramedic Training",750000],
		["donator",[safelicense,safelicense,safelicense,safelicense,safelicense],"Donator License",999999999],
		["viplicense",[safelicense,safelicense,safelicense,safelicense,safelicense],"VIP Donator License",999999999],
		["mgslicense",[safelicense,safelicense,safelicense,safelicense,safelicense],"METAL GEAR License",999999999],
		["jarlicense",[safelicense,safelicense,safelicense,safelicense,safelicense],"The Jarhead License",999999999],
		["bonglicense",[safelicense,safelicense,safelicense,safelicense,safelicense],"Bong Reseller License",999999999],
		["grelllicense",[safelicense,safelicense,safelicense,safelicense,safelicense],"SS License",999999999],
		["colelicense",[safelicense,safelicense,safelicense,safelicense,safelicense],"The Bond License",999999999],
		["karmalicense",[safelicense,safelicense,safelicense,safelicense,safelicense],"KarmaIsABitch",999999999],
		["highcaliberrifle",[licenseflag2,licenseflag2,licenseflag2,licenseflag2,licenseflag2],"High Caliber Rifle License",250000],
		["newslicense",[atmnews,atmnews,atmnews,atmnews,atmnews],"News Reporters License",1500000],
		["hitman",[safelicense,safelicense,safelicense,safelicense,safelicense],"Hitman License",500000]
        //["assassin",[agunshop,agunshop,safelicense,safelicense],"Assassin Training",30000]
    ];

["INV_LicenseOwner", []] call stats_init_variable;