if (!(createDialog "K6_Menu")) exitWith {hint "Dialog Error!";};

#define AdminConsol 1000
#define AdminPlayers 2006

private ["_c", "_player_variable_name", "_player_variable", "_Findex"];

_c = 0;
_player_variable_name = "";
_Findex = -1;

for [{_c=0}, {_c < (count PlayerStringArray)}, {_c=_c+1}] do {
	_player_variable_name = PlayerStringArray select _c;
	_player_variable = missionNamespace getVariable _player_variable_name;
	
	if ([_player_variable] call player_exists) then {
		private["_player_name"];
		_player_name = (name _player_variable);
		_Findex = lbAdd [AdminPlayers, format ["%1 - (%2)", _player_variable_name, _player_name]];
		lbSetData [AdminPlayers, _Findex, format["%1", _player_variable]];	
	};
};


lbAdd [AdminConsol, "Lockpicks"];
lbAdd [AdminConsol, "Double ATM Money"];
lbAdd [AdminConsol, "Money"];
lbAdd [AdminConsol, "Pistol"];
lbAdd [AdminConsol, "RangeFinder"];
lbAdd [AdminConsol, "Large Repair Kit"];
lbAdd [AdminConsol, "Refuel Can"];
lbAdd [AdminConsol, "Medkit"];
lbAdd [AdminConsol, "GPS NV Binoc"];
lbAdd [AdminConsol, "Pimp My Ride"];
lbAdd [AdminConsol, "Fix My Ride"];
lbAdd [AdminConsol, "Cheap Gunz"];
lbAdd [AdminConsol, "Decent Gunz"];
lbAdd [AdminConsol, "Quiet Gunz"];
lbAdd [AdminConsol, "Sniper Gunz"];
lbAdd [AdminConsol, "Pwn Gunz"];
lbAdd [AdminConsol, "Remote Bomb"];
lbAdd [AdminConsol, "Time Bomb"];
lbAdd [AdminConsol, "Activation Bomb"];
lbAdd [AdminConsol, "Speed Bomb"];
lbAdd [AdminConsol, "Suicide Bomb"];
lbAdd [AdminConsol, "Remote Control"];
lbAdd [AdminConsol, "Defuser"];
lbAdd [AdminConsol, "Lighter"];
lbAdd [AdminConsol, "10 Bank insurance"];
lbAdd [AdminConsol, "Magic Box (local)"];
lbAdd [AdminConsol, "10 Mackerel"];
lbAdd [AdminConsol, "10 Herring"];
lbAdd [AdminConsol, "10 Deep Sea Bass"];
lbAdd [AdminConsol, "20 Wheat"];
lbAdd [AdminConsol, "Bread"];
lbAdd [AdminConsol, "20 Donut"];
lbAdd [AdminConsol, "Larger"];
lbAdd [AdminConsol, "Bitter"];
lbAdd [AdminConsol, "Vodka"];
lbAdd [AdminConsol, "Smirnoff ICE"];
lbAdd [AdminConsol, "Wiskey"];
lbAdd [AdminConsol, "White Wine"];
lbAdd [AdminConsol, "Red Wine"];
lbAdd [AdminConsol, "10 Wood"];
lbAdd [AdminConsol, "10 Iron"];
lbAdd [AdminConsol, "10 Mineral oil"];
lbAdd [AdminConsol, "10 Electronic components"];
lbAdd [AdminConsol, "10 Silicon"];
lbAdd [AdminConsol, "10 Copper"];
lbAdd [AdminConsol, "10 Steel"];
lbAdd [AdminConsol, "10 Black powder"];
lbAdd [AdminConsol, "10 Sulfur"];
lbAdd [AdminConsol, "10 Coal"];
lbAdd [AdminConsol, "10 Diamond rock"];
lbAdd [AdminConsol, "10 Gold"];
lbAdd [AdminConsol, "10 Oil"];
lbAdd [AdminConsol, "10 Petroleum"];
lbAdd [AdminConsol, "10 Glass"];
lbAdd [AdminConsol, "10 Plastic"];
lbAdd [AdminConsol, "10 Sand"];
lbAdd [AdminConsol, "Steel wool"];
lbAdd [AdminConsol, "Whale"];
lbAdd [AdminConsol, "10 Unprocessed Cocaine"];
lbAdd [AdminConsol, "10 Unprocessed Marijuana"];
lbAdd [AdminConsol, "10 Unprocessed LSD"];
lbAdd [AdminConsol, "10 Unprocessed Heroin"];
lbAdd [AdminConsol, "10 Marijuana"];
lbAdd [AdminConsol, "10 Cocaine"];
lbAdd [AdminConsol, "10 LSD"];
lbAdd [AdminConsol, "10 Heroin"];
lbAdd [AdminConsol, "Marijuana Seed"];
lbAdd [AdminConsol, "Drug-Shed"];
lbAdd [AdminConsol, "Marijuana (not processed)"];
lbAdd [AdminConsol, "Mobile Phone"];
lbAdd [AdminConsol, "Roadblock"];
lbAdd [AdminConsol, "Speed Trap"];
lbAdd [AdminConsol, "Bar Gate"];
lbAdd [AdminConsol, "Sign Checkpoint"];
lbAdd [AdminConsol, "Bunker (Small)"];
lbAdd [AdminConsol, "Road cone (light)"];
lbAdd [AdminConsol, "Road barrier (light)"];
lbAdd [AdminConsol, "Diamond Ring"];
lbAdd [AdminConsol, "Expensive Diamond Ring"];
lbAdd [AdminConsol, "Vehicle Ammo"];
lbAdd [AdminConsol, "Hideout"];
lbAdd [AdminConsol, "Radio jammer"];
lbAdd [AdminConsol, "Lockpick"];
lbAdd [AdminConsol, "Gas mask"];
lbAdd [AdminConsol, "Shovel"];
lbAdd [AdminConsol, "Pickaxe"];
lbAdd [AdminConsol, "JackHammer"];
lbAdd [AdminConsol, "Spikestrip"];
lbAdd [AdminConsol, "Storage box"];
lbAdd [AdminConsol, "Camo Net"];
lbAdd [AdminConsol, "RazorWire"];
lbAdd [AdminConsol, "Barricade"];
lbAdd [AdminConsol, "Fireplace"];
lbAdd [AdminConsol, "MTent"];
lbAdd [AdminConsol, "Road Barrier"];
lbAdd [AdminConsol, "Trench"];
lbAdd [AdminConsol, "supgrade1"];
lbAdd [AdminConsol, "supgrade2"];
lbAdd [AdminConsol, "supgrade3"];
lbAdd [AdminConsol, "supgrade4"];
lbAdd [AdminConsol, "supgrade5"];
lbAdd [AdminConsol, "House"];
lbAdd [AdminConsol, "Small House"];
lbAdd [AdminConsol, "Warning Tape"];
lbAdd [AdminConsol, "20 Apple"];
lbAdd [AdminConsol, "5 Apple Pie"];
lbAdd [AdminConsol, "Gate"];
lbAdd [AdminConsol, "Sandbag Wall"];
lbAdd [AdminConsol, "Barracks"];
lbAdd [AdminConsol, "Small Tower"];
lbAdd [AdminConsol, "Fence"];
lbAdd [AdminConsol, "10 Sturgeon"];
lbAdd [AdminConsol, "20 Caviar"];
lbAdd [AdminConsol, ""];
lbAdd [AdminConsol, "[---Admin Related Commands---]"];
lbAdd [AdminConsol, "Self Teleport"];
lbAdd [AdminConsol, "Self Invisibility (disabled)"];
lbAdd [AdminConsol, "Self Visibility (disabled)"];
lbAdd [AdminConsol, "Spawn Yourself A Soldier (disabled)"];
lbAdd [AdminConsol, "Inf Ammo (disabled)"];
lbAdd [AdminConsol, "Admin Camera (Toggle)"];
lbAdd [AdminConsol, "Carmagedon"];
lbAdd [AdminConsol, "Remove player weapons"];
lbAdd [AdminConsol, "Kill player"];
lbAdd [AdminConsol, "Destroy player vehicle"];
lbAdd [AdminConsol, "Save player stats"];
lbAdd [AdminConsol, "Restore player stats"];
lbAdd [AdminConsol, "PMC - 1: Black/White List Dialog"];
lbAdd [AdminConsol, "+1 Hour time"];
lbAdd [AdminConsol, "-1 Hour time"];
lbAdd [AdminConsol, "Reset time(40m dy, 20m nt)"];
lbAdd [AdminConsol, "Reset time(60m dy, 30m nt)"];